# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise

# Site Settings
locale: "en-US"
title: Ethan's Blog
email: emorchy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the early stages of this site. Until I get a feel for the software and until I make my first project post, this description will remain up.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: emorchy
words_per_minute: 200

# Build settings
markdown: kramdown
  #remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-toc
  - jekyll-spaceship

include:
  - .htaccess
  - _pages
  - _includes
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site Author
author:
  name             : "Ethan Morchy"
    #avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Cybersecurity specialist with an emphasis on binary exploitation and cryptography."
  location         : "Los Angeles, CA"
  links:
    #- label: "This website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://emorchy.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emorchy"

# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: false
      toc: true
      toc_label: "Contents"
      share: false
      related: true
